service: hello-serverless

provider:
  name: aws
  runtime: nodejs12.x

environment:
  marketTable: Market
  
custom:
  dynamodb:
    stages:
      - dev

iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:UpdateItem
      Resource: 
        - { "Fn::GetAtt": ["MarketDynamoDbTable", "Arn" ] }

functions:
  seek:
    handler: api/handler.seek
    events:
      - http:
          path: /item
          method: get
  buy:
    handler: api/handler.buy
    events:
      - http:
          path: /item
          method: post

resources:
  Resources:
    MarketDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
            - AttributeName: "itemID"
              AttributeType: "S" 
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5  
        KeySchema:
            - AttributeName: "itemID"
              KeyType: "HASH"
        TableName: "Market"

plugins:
  - serverless-offline
  - serverless-dynamodb-local